[window]
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/blood_moon.toml"
]

[keyboard]
bindings = [
{ key = "Up", mods = "Shift", action = "ScrollLineUp" },
{ key = "Down", mods = "Shift", action = "ScrollLineDown" },
]

[scrolling]
history = 100000
